### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by jonahbrennan** [Nathanlauga/nba-predictor#1]
Hi Nathan,

Thanks to your dataset on Kaggle, we created an NBA game predictor.  
You can check it out here: https://nba-game-predictor.herokuapp.com/

I'm currently using your get_games.py to scrape a fresh set and I'm wondering what the steps are to get to the games.csv and games_details,csv ...  formats that you posted?

Thanks for the great work, your data has been a lot of fun to work with!

**Comment by Nathanlauga** [comment]
Hi @jonahbrennan ! 
First of all, great job on the app, if you have the code source to share I'll be glad! 

Regarding getting new games I create a script to retrieve them based on the last date of games.csv you can access it there : [get_new_games.py](https://github.com/Nathanlauga/nba-predictor/blob/master/scripts/get_new_games.py).

You need to have the old data in a `data/` directory.

Best regards and I hope you'll continue to have a lot of fun ;)

**Comment by jonahbrennan** [comment]
Thanks! it's a fun project.
I got get_new_games to work no worries. I guess I was asking about the steps to generating the games_details.csv.  I'd like to incorporate real time updates directly from the api but not sure on the endpoints. I'll have to take a closer look at your code.

I made some tweaks to the prediction model and put in a roster advantage for close calls.
check it out here:
https://github.com/firehelmet1/final_project
look in Frontend/nba_games

**Comment by Nathanlauga** [comment]
To generate games_details.csv I just use ann endpoint of the API. And the code is available inside `utils.py` with the `get_game_detail` function : 

```
def get_game_detail(game_id):
    if type(game_id) != type(str()):
        game_id = '00' + str(game_id)
    url = 'https://stats.nba.com/stats/boxscoretraditionalv2?EndPeriod=10&EndRange=0&GameID='+str(game_id) \
        + '&RangeType=0&Season=2019-20&SeasonType=Regular+Season&StartPeriod=1&StartRange=0'

    df = get_data(url, datasets_name=['PlayerStats'])
    return df['PlayerStats']
```

Thanks for sharing !
