### ISSUE TITLE
Has the endpoint been changed?

### ISSUE THREAD

**Issue by jonahbrennan** [Nathanlauga/nba-predictor#2]
I ran  python get_new_games.py to update the data and I don't seem to be able to connect.
Did they change things at stats.nba?

https://stats.nba.com/stats/scoreboardV2?DayOffset=0&LeagueID=00&gameDate=2020-01-27

**Comment by jonahbrennan** [comment]
Found some info on the issue from:
https://github.com/swar/nba_api/issues/124

So in summary, for a cURL call I have found that after Jan-23 you must now have the following
// As of Jan-23-2020 these Headers are Required for CURL to stats.nba.com
//-H 'Referer: https://stats.nba.com'
//-H 'Origin: https://stats.nba.com'
//-H 'x-nba-stats-token: true'
//-H 'x-nba-stats-origin: stats'
//-H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36'

curl 'https://stats.nba.com/stats/commonplayerinfo?LeagueID=&PlayerID=2544' -H 'Referer: https://stats.nba.com' -H 'Origin: https://stats.nba.com' -H 'x-nba-stats-origin: stats' -H 'x-nba-stats-token: true' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36'

**Comment by Nathanlauga** [comment]
Thanks for the information ! It's fixed now :)
